import Mathlib.NumberTheory.LegendreSymbol.AddCharacter
import Mathlib.NumberTheory.MulChar.Basic
import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed
import SerreNumberTheoryAI.Formalization.Chapter01.LegendreSymbol

/-!
# Quadratic reciprocity: source-shaped Gauss-sum infrastructure

Independent formalization infrastructure for Serre, Chapter 1, §3.3, Theorem 6.
Source metadata only: Japanese edition, printed pp. 10–11, uploaded PDF pp. 20–21.

The target reciprocity theorem is intentionally not closed by mathlib's ready-made
quadratic-reciprocity or Gauss-sum theorems. This file starts from the source objects:
a primitive `l`-th root of unity and a Gauss sum with the project Legendre sign.
-/

namespace SerreNumberTheoryAI

section QuadraticReciprocity

variable (l p : ℕ) [Fact l.Prime] [Fact p.Prime]

/-- Distinct primes remain nonzero after casting `l` into the prime field of characteristic `p`. -/
theorem zmod_prime_cast_ne_zero_of_distinct (hlp : l ≠ p) :
    (l : ZMod p) ≠ 0 := by
  rw [ne_eq, ZMod.natCast_eq_zero_iff]
  intro hdiv
  rcases (Nat.dvd_prime (Fact.out : l.Prime)).mp hdiv with hp1 | hpl
  · exact (Fact.out : p.Prime).ne_one hp1
  · exact hlp hpl.symm

/-- In an algebraic closure of `F_p`, distinct primes `l` and `p` give a primitive `l`-th root. -/
theorem exists_primitive_lth_root_algClosure (hlp : l ≠ p) :
    ∃ w : AlgebraicClosure (ZMod p), IsPrimitiveRoot w l := by
  letI : NeZero (l : ZMod p) := ⟨zmod_prime_cast_ne_zero_of_distinct l p hlp⟩
  exact HasEnoughRootsOfUnity.exists_primitiveRoot (AlgebraicClosure (ZMod p)) l

/-- The additive character `x ↦ w^x` attached to an `l`-th root of unity. -/
def serreRootAddChar
    {K : Type*} [CommMonoid K]
    (w : K) (hw : w ^ l = 1) : AddChar (ZMod l) K := by
  letI : NeZero l := ⟨(Fact.out : l.Prime).ne_zero⟩
  exact AddChar.zmodChar l hw

@[simp]
theorem serreRootAddChar_apply
    {K : Type*} [CommMonoid K]
    (w : K) (hw : w ^ l = 1) (x : ZMod l) :
    serreRootAddChar l w hw x = w ^ x.val := by
  letI : NeZero l := ⟨(Fact.out : l.Prime).ne_zero⟩
  rfl

/-- The source-shaped Gauss sum `∑ (x/l) w^x`, using the project's integer sign layer. -/
noncomputable def serreGaussSum
    (w : AlgebraicClosure (ZMod p)) : AlgebraicClosure (ZMod p) :=
  ∑ x : ZMod l, (legendreSign l x : AlgebraicClosure (ZMod p)) * w ^ x.val

/-- Re-express the Gauss sum through the additive character generated by the same root. -/
theorem serreGaussSum_eq_addChar_sum
    (w : AlgebraicClosure (ZMod p)) (hw : w ^ l = 1) :
    serreGaussSum l p w =
      ∑ x : ZMod l,
        (legendreSign l x : AlgebraicClosure (ZMod p)) * serreRootAddChar l w hw x := by
  simp [serreGaussSum, serreRootAddChar_apply]

/-- For a nonzero prime-field element, the square has Legendre sign `1`. -/
theorem legendreSign_sq_eq_one_of_ne_zero
    (hl : l ≠ 2) (x : ZMod l) (hx : x ≠ 0) :
    legendreSign l (x ^ 2) = 1 := by
  rw [pow_two, legendreSign_mul l hl]
  rcases legendreSign_eq_one_or_neg_one_of_ne_zero l x hx with h | h
  · rw [h]
    norm_num
  · rw [h]
    norm_num

/-- Pulling out a minus sign agrees with multiplying by the integer Legendre sign of `-1`. -/
theorem legendreSign_neg
    (hl : l ≠ 2) (x : ZMod l) :
    legendreSign l (-x) = legendreSignInt l (-1) * legendreSign l x := by
  have hminus : ((-1 : ℤ) : ZMod l) = -1 := by norm_num
  rw [legendreSignInt, hminus]
  simpa only [neg_one_mul] using
    legendreSign_mul l hl (-1 : ZMod l) x

/-- Package the project Legendre sign as a generic multiplicative character. -/
noncomputable def serreLegendreMulChar (hl : l ≠ 2) : MulChar (ZMod l) ℤ where
  toFun := legendreSign l
  map_one' := legendreSign_one l
  map_mul' := legendreSign_mul l hl
  map_nonunit' := by
    intro x hx
    have hx0 : x = 0 := by
      by_contra hne
      exact hx (isUnit_iff_ne_zero.mpr hne)
    subst x
    exact legendreSign_zero l

@[simp]
theorem serreLegendreMulChar_apply (hl : l ≠ 2) (x : ZMod l) :
    serreLegendreMulChar l hl x = legendreSign l x :=
  rfl

/-- The project Legendre multiplicative character is nontrivial for an odd prime. -/
theorem serreLegendreMulChar_ne_one (hl : l ≠ 2) :
    serreLegendreMulChar l hl ≠ 1 := by
  obtain ⟨u, hu, _⟩ :=
    (Subgroup.index_eq_two_iff_exists_notMem_and).mp
      (finiteFieldNonzeroSquares_index (ZMod l) l hl)
  have hhalf_ne : finiteFieldHalfPowerCharacter (ZMod l) u ≠ 1 := by
    intro hhalf
    exact hu ((mem_finiteFieldNonzeroSquares_iff_halfPowerCharacter_eq_one
      (ZMod l) l hl u).mpr hhalf)
  have hhalf_neg : finiteFieldHalfPowerCharacter (ZMod l) u = -1 :=
    (finiteFieldHalfPowerCharacter_eq_one_or_neg_one (ZMod l) l hl u).resolve_left hhalf_ne
  have hval_neg : legendreValue l (u : ZMod l) = -1 := by
    rw [legendreValue_eq_halfPowerCharacter_coe l (u : ZMod l) u.ne_zero]
    simpa using congrArg (fun v : (ZMod l)ˣ => (v : ZMod l)) hhalf_neg
  have hl3 : 3 ≤ l := by
    have hl2 : 2 ≤ l := (Fact.out : l.Prime).two_le
    omega
  letI : Fact (2 < l) := ⟨by omega⟩
  have hsign_neg : legendreSign l (u : ZMod l) = -1 := by
    simp [legendreSign, u.ne_zero, hval_neg]
  intro htriv
  have happ := congrArg (fun χ : MulChar (ZMod l) ℤ => χ (u : ZMod l)) htriv
  have hone : (1 : MulChar (ZMod l) ℤ) (u : ZMod l) = 1 :=
    MulChar.one_apply u.isUnit
  rw [serreLegendreMulChar_apply, hsign_neg, hone] at happ
  norm_num at happ

/-- The sum of the project Legendre signs over the prime field is zero. -/
theorem sum_legendreSign_eq_zero (hl : l ≠ 2) :
    ∑ x : ZMod l, legendreSign l x = 0 := by
  simpa using
    (MulChar.sum_eq_zero_of_ne_one
      (R := ZMod l) (R' := ℤ) (serreLegendreMulChar_ne_one l hl))

end QuadraticReciprocity

end SerreNumberTheoryAI
