import Mathlib.Algebra.GroupWithZero.Units.Equiv
import Mathlib.NumberTheory.LegendreSymbol.AddCharacter
import Mathlib.NumberTheory.GaussSum
import Mathlib.NumberTheory.MulChar.Basic
import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed
import SerreNumberTheoryAI.Formalization.Chapter01.LegendreSymbol

/-!
# Quadratic reciprocity: source-shaped Gauss-sum infrastructure

Independent formalization infrastructure for Serre, Chapter 1, §3.3, Theorem 6.
Source metadata only: Japanese edition, printed pp. 10–11, uploaded PDF pp. 20–21.

The target reciprocity theorem is intentionally not closed by mathlib's ready-made
quadratic-reciprocity or Gauss-sum theorems. This file starts from the source objects:
a primitive `l`-th root of unity and a Gauss sum with the project Legendre sign.
-/

namespace SerreNumberTheoryAI

section QuadraticReciprocity

variable (l p : ℕ) [Fact l.Prime] [Fact p.Prime]

/-- Distinct primes remain nonzero after casting `l` into the prime field of characteristic `p`. -/
theorem zmod_prime_cast_ne_zero_of_distinct (hlp : l ≠ p) :
    (l : ZMod p) ≠ 0 := by
  rw [ne_eq, ZMod.natCast_eq_zero_iff]
  intro hdiv
  rcases (Nat.dvd_prime (Fact.out : l.Prime)).mp hdiv with hp1 | hpl
  · exact (Fact.out : p.Prime).ne_one hp1
  · exact hlp hpl.symm

/-- In an algebraic closure of `F_p`, distinct primes `l` and `p` give a primitive `l`-th root. -/
theorem exists_primitive_lth_root_algClosure (hlp : l ≠ p) :
    ∃ w : AlgebraicClosure (ZMod p), IsPrimitiveRoot w l := by
  letI : NeZero (l : ZMod p) := ⟨zmod_prime_cast_ne_zero_of_distinct l p hlp⟩
  exact HasEnoughRootsOfUnity.exists_primitiveRoot (AlgebraicClosure (ZMod p)) l

/-- The additive character `x ↦ w^x` attached to an `l`-th root of unity. -/
def serreRootAddChar
    {K : Type*} [CommMonoid K]
    (w : K) (hw : w ^ l = 1) : AddChar (ZMod l) K := by
  letI : NeZero l := ⟨(Fact.out : l.Prime).ne_zero⟩
  exact AddChar.zmodChar l hw

@[simp]
theorem serreRootAddChar_apply
    {K : Type*} [CommMonoid K]
    (w : K) (hw : w ^ l = 1) (x : ZMod l) :
    serreRootAddChar l w hw x = w ^ x.val := by
  letI : NeZero l := ⟨(Fact.out : l.Prime).ne_zero⟩
  rfl

/-- The source-shaped Gauss sum `∑ (x/l) w^x`, using the project's integer sign layer. -/
noncomputable def serreGaussSum
    (w : AlgebraicClosure (ZMod p)) : AlgebraicClosure (ZMod p) :=
  ∑ x : ZMod l, (legendreSign l x : AlgebraicClosure (ZMod p)) * w ^ x.val

/-- Re-express the Gauss sum through the additive character generated by the same root. -/
theorem serreGaussSum_eq_addChar_sum
    (w : AlgebraicClosure (ZMod p)) (hw : w ^ l = 1) :
    serreGaussSum l p w =
      ∑ x : ZMod l,
        (legendreSign l x : AlgebraicClosure (ZMod p)) * serreRootAddChar l w hw x := by
  simp [serreGaussSum, serreRootAddChar_apply]

/-- For a nonzero prime-field element, the square has Legendre sign `1`. -/
theorem legendreSign_sq_eq_one_of_ne_zero
    (hl : l ≠ 2) (x : ZMod l) (hx : x ≠ 0) :
    legendreSign l (x ^ 2) = 1 := by
  rw [pow_two, legendreSign_mul l hl]
  rcases legendreSign_eq_one_or_neg_one_of_ne_zero l x hx with h | h
  · rw [h]
    norm_num
  · rw [h]
    norm_num

/-- Pulling out a minus sign agrees with multiplying by the integer Legendre sign of `-1`. -/
theorem legendreSign_neg
    (hl : l ≠ 2) (x : ZMod l) :
    legendreSign l (-x) = legendreSignInt l (-1) * legendreSign l x := by
  have hminus : ((-1 : ℤ) : ZMod l) = -1 := by norm_num
  rw [legendreSignInt, hminus]
  simpa only [neg_one_mul] using
    legendreSign_mul l hl (-1 : ZMod l) x

/-- Package the project Legendre sign as a generic multiplicative character. -/
noncomputable def serreLegendreMulChar (hl : l ≠ 2) : MulChar (ZMod l) ℤ where
  toFun := legendreSign l
  map_one' := legendreSign_one l
  map_mul' := legendreSign_mul l hl
  map_nonunit' := by
    intro x hx
    have hx0 : x = 0 := by
      by_contra hne
      exact hx (isUnit_iff_ne_zero.mpr hne)
    subst x
    exact legendreSign_zero l

@[simp]
theorem serreLegendreMulChar_apply (hl : l ≠ 2) (x : ZMod l) :
    serreLegendreMulChar l hl x = legendreSign l x :=
  rfl

/-- The project Legendre multiplicative character is nontrivial for an odd prime. -/
theorem serreLegendreMulChar_ne_one (hl : l ≠ 2) :
    serreLegendreMulChar l hl ≠ 1 := by
  obtain ⟨u, hu, _⟩ :=
    (Subgroup.index_eq_two_iff_exists_notMem_and).mp
      (finiteFieldNonzeroSquares_index (ZMod l) l hl)
  have hhalf_ne : finiteFieldHalfPowerCharacter (ZMod l) u ≠ 1 := by
    intro hhalf
    exact hu ((mem_finiteFieldNonzeroSquares_iff_halfPowerCharacter_eq_one
      (ZMod l) l hl u).mpr hhalf)
  have hhalf_neg : finiteFieldHalfPowerCharacter (ZMod l) u = -1 :=
    (finiteFieldHalfPowerCharacter_eq_one_or_neg_one (ZMod l) l hl u).resolve_left hhalf_ne
  have hval_neg : legendreValue l (u : ZMod l) = -1 := by
    rw [legendreValue_eq_halfPowerCharacter_coe l (u : ZMod l) u.ne_zero]
    simpa using congrArg (fun v : (ZMod l)ˣ => (v : ZMod l)) hhalf_neg
  have hl3 : 3 ≤ l := by
    have hl2 : 2 ≤ l := (Fact.out : l.Prime).two_le
    omega
  letI : Fact (2 < l) := ⟨by omega⟩
  have hval_ne : legendreValue l (u : ZMod l) ≠ 1 := by
    rw [hval_neg]
    exact ZMod.neg_one_ne_one
  have hsign_neg : legendreSign l (u : ZMod l) = -1 := by
    simp [legendreSign, u.ne_zero, hval_ne]
  intro htriv
  have happ := congrArg (fun χ : MulChar (ZMod l) ℤ => χ (u : ZMod l)) htriv
  have hone : (1 : MulChar (ZMod l) ℤ) (u : ZMod l) = 1 :=
    MulChar.one_apply u.isUnit
  rw [serreLegendreMulChar_apply, hsign_neg, hone] at happ
  norm_num at happ

/-- The sum of the project Legendre signs over the prime field is zero. -/
theorem sum_legendreSign_eq_zero (hl : l ≠ 2) :
    ∑ x : ZMod l, legendreSign l x = 0 := by
  simpa using
    (MulChar.sum_eq_zero_of_ne_one
      (R := ZMod l) (R' := ℤ) (serreLegendreMulChar_ne_one l hl))

/--
The source coefficient `C_u`, written as a total field sum. The term at `t = 0` is always `1`,
so subtracting `1` is exactly the source's restriction to `t ≠ 0`.
-/
noncomputable def serreGaussCoefficient (u : ZMod l) : ℤ :=
  (∑ t : ZMod l, legendreSign l (1 - u / t)) - 1

/-- The source coefficient at zero is `l - 1`. -/
theorem serreGaussCoefficient_zero :
    serreGaussCoefficient l 0 = (l : ℤ) - 1 := by
  simp [serreGaussCoefficient, ZMod.card]

/-- Every nonzero source coefficient is `-1`. -/
theorem serreGaussCoefficient_eq_neg_one_of_ne_zero
    (hl : l ≠ 2) (u : ZMod l) (hu : u ≠ 0) :
    serreGaussCoefficient l u = -1 := by
  let eSub : Equiv.Perm (ZMod l) :=
    { toFun := fun z => 1 - z
      invFun := fun z => 1 - z
      left_inv := by
        intro z
        simp
      right_inv := by
        intro z
        simp }
  let e : Equiv.Perm (ZMod l) := (Equiv.divLeft₀ u hu).trans eSub
  have he_apply (t : ZMod l) : e t = 1 - u / t := by
    rfl
  have hsum :
      (∑ t : ZMod l, legendreSign l (1 - u / t)) =
        ∑ s : ZMod l, legendreSign l s := by
    exact Fintype.sum_bijective e e.bijective _ _ fun t => by
      rw [he_apply]
  rw [serreGaussCoefficient, hsum, sum_legendreSign_eq_zero l hl]
  norm_num


/-- The powers of a primitive `l`-th root sum to zero over `ZMod l`. -/
theorem sum_primitive_lth_root_powers_eq_zero
    (w : AlgebraicClosure (ZMod p)) (hw : IsPrimitiveRoot w l) :
    ∑ u : ZMod l, w ^ u.val = 0 := by
  letI : NeZero l := ⟨(Fact.out : l.Prime).ne_zero⟩
  have hne :
      serreRootAddChar l w hw.pow_eq_one ≠ 1 := by
    rw [AddChar.zmod_char_ne_one_iff]
    have hvalone : (1 : ZMod l).val = 1 := by
      rw [ZMod.val_one_eq_one_mod]
      exact Nat.mod_eq_of_lt (Fact.out : l.Prime).one_lt
    rw [serreRootAddChar_apply, hvalone, pow_one]
    exact hw.ne_one (Fact.out : l.Prime).one_lt
  simpa [serreRootAddChar_apply] using
    (AddChar.sum_eq_zero_of_ne_one hne)

/--
The source coefficient evaluation collapses the weighted root-of-unity sum to the scalar `l`.
This is the final finite-sum step in Serre's proof of the Gauss-square identity.
-/
theorem sum_serreGaussCoefficient_mul_rootPower
    (hl : l ≠ 2) (w : AlgebraicClosure (ZMod p)) (hw : IsPrimitiveRoot w l) :
    ∑ u : ZMod l,
        (serreGaussCoefficient l u : AlgebraicClosure (ZMod p)) * w ^ u.val =
      (l : AlgebraicClosure (ZMod p)) := by
  have hcoeff (u : ZMod l) :
      (serreGaussCoefficient l u : AlgebraicClosure (ZMod p)) =
        -1 + if u = 0 then (l : AlgebraicClosure (ZMod p)) else 0 := by
    by_cases hu : u = 0
    · subst u
      rw [serreGaussCoefficient_zero]
      push_cast
      simp
      ring
    · rw [serreGaussCoefficient_eq_neg_one_of_ne_zero l hl u hu]
      simp [hu]
  have hroot : ∑ u : ZMod l, w ^ u.val = 0 :=
    sum_primitive_lth_root_powers_eq_zero l p w hw
  simp_rw [hcoeff, add_mul]
  rw [Finset.sum_add_distrib]
  simp [hroot]


/--
Expand the square of the source Gauss sum and collect terms by their additive total
`u = t + z`. This is the double-sum rearrangement appearing at the start of Serre's
proof of the first Gauss-sum lemma.
-/
theorem serreGaussSum_sq_eq_source_convolution
    (hl : l ≠ 2) (w : AlgebraicClosure (ZMod p)) (hw : w ^ l = 1) :
    serreGaussSum l p w ^ 2 =
      ∑ u : ZMod l,
        (∑ t : ZMod l,
          (legendreSign l (t * (u - t)) : AlgebraicClosure (ZMod p))) *
          w ^ u.val := by
  have hfixed (t : ZMod l) :
      (∑ z : ZMod l,
        ((legendreSign l t : ℤ) : AlgebraicClosure (ZMod p)) *
            serreRootAddChar l w hw t *
          (((legendreSign l z : ℤ) : AlgebraicClosure (ZMod p)) *
            serreRootAddChar l w hw z)) =
        ∑ u : ZMod l,
          ((legendreSign l (t * (u - t)) : ℤ) :
              AlgebraicClosure (ZMod p)) *
            serreRootAddChar l w hw u := by
    let e : Equiv.Perm (ZMod l) := Equiv.addLeft t
    refine Fintype.sum_bijective e e.bijective _ _ ?_
    intro z
    change
      ((legendreSign l t : ℤ) : AlgebraicClosure (ZMod p)) *
            serreRootAddChar l w hw t *
          (((legendreSign l z : ℤ) : AlgebraicClosure (ZMod p)) *
            serreRootAddChar l w hw z) =
        ((legendreSign l (t * ((t + z) - t)) : ℤ) :
            AlgebraicClosure (ZMod p)) *
          serreRootAddChar l w hw (t + z)
    have hsub : t + z - t = z := by ring
    rw [hsub, legendreSign_mul l hl]
    push_cast
    rw [(serreRootAddChar l w hw).map_add_eq_mul]
    ring
  rw [serreGaussSum_eq_addChar_sum l p w hw, pow_two,
    Fintype.sum_mul_sum]
  calc
    (∑ t : ZMod l, ∑ z : ZMod l,
        (((legendreSign l t : ℤ) : AlgebraicClosure (ZMod p)) *
            serreRootAddChar l w hw t) *
          (((legendreSign l z : ℤ) : AlgebraicClosure (ZMod p)) *
            serreRootAddChar l w hw z)) =
      ∑ t : ZMod l, ∑ u : ZMod l,
        ((legendreSign l (t * (u - t)) : ℤ) :
            AlgebraicClosure (ZMod p)) *
          serreRootAddChar l w hw u := by
      apply Finset.sum_congr rfl
      intro t _
      exact hfixed t
    _ = ∑ u : ZMod l, ∑ t : ZMod l,
        ((legendreSign l (t * (u - t)) : ℤ) :
            AlgebraicClosure (ZMod p)) *
          serreRootAddChar l w hw u := by
      rw [Finset.sum_comm]
    _ = ∑ u : ZMod l,
        (∑ t : ZMod l,
          ((legendreSign l (t * (u - t)) : ℤ) :
            AlgebraicClosure (ZMod p))) *
          serreRootAddChar l w hw u := by
      apply Finset.sum_congr rfl
      intro u _
      rw [Finset.sum_mul]
    _ = ∑ u : ZMod l,
        (∑ t : ZMod l,
          (legendreSign l (t * (u - t)) : AlgebraicClosure (ZMod p))) *
          w ^ u.val := by
      simp [serreRootAddChar_apply]


/--
For each additive total `u`, the inner convolution of Legendre signs is the source
coefficient multiplied by the supplementary sign at `-1`.
-/
theorem sum_legendreSign_product_eq_sign_mul_coefficient
    (hl : l ≠ 2) (u : ZMod l) :
    (∑ t : ZMod l, legendreSign l (t * (u - t))) =
      legendreSignInt l (-1) * serreGaussCoefficient l u := by
  rw [serreGaussCoefficient]
  have hterm (t : ZMod l) :
      legendreSign l (t * (u - t)) =
        legendreSignInt l (-1) * legendreSign l (1 - u / t) -
          if t = 0 then legendreSignInt l (-1) else 0 := by
    by_cases ht : t = 0
    · subst t
      simp [legendreSignInt]
    · have hfactor :
          t * (u - t) = (-t ^ 2) * (1 - u / t) := by
        field_simp [ht]
        ring
      rw [if_neg ht, sub_zero, hfactor, legendreSign_mul l hl]
      rw [show -t ^ 2 = (-1 : ZMod l) * t ^ 2 by ring,
        legendreSign_mul l hl, legendreSign_sq_eq_one_of_ne_zero l hl t ht]
      simp [legendreSignInt]
  calc
    (∑ t : ZMod l, legendreSign l (t * (u - t))) =
        ∑ t : ZMod l,
          (legendreSignInt l (-1) * legendreSign l (1 - u / t) -
            if t = 0 then legendreSignInt l (-1) else 0) := by
      apply Finset.sum_congr rfl
      intro t _
      exact hterm t
    _ = legendreSignInt l (-1) *
        ((∑ t : ZMod l, legendreSign l (1 - u / t)) - 1) := by
      rw [Finset.sum_sub_distrib, ← Finset.mul_sum]
      simp
      ring


/-- Serre's first Gauss-sum lemma, before rewriting the sign at `-1` by Theorem 5(ii). -/
theorem serreGaussSum_sq_eq_legendreSign_neg_one_mul
    (hl : l ≠ 2) (w : AlgebraicClosure (ZMod p)) (hw : IsPrimitiveRoot w l) :
    serreGaussSum l p w ^ 2 =
      (legendreSignInt l (-1) : AlgebraicClosure (ZMod p)) *
        (l : AlgebraicClosure (ZMod p)) := by
  rw [serreGaussSum_sq_eq_source_convolution l p hl w hw.pow_eq_one]
  have hinner (u : ZMod l) :
      (∑ t : ZMod l,
          (legendreSign l (t * (u - t)) : AlgebraicClosure (ZMod p))) =
        (legendreSignInt l (-1) : AlgebraicClosure (ZMod p)) *
          (serreGaussCoefficient l u : AlgebraicClosure (ZMod p)) := by
    have h := congrArg
      (fun z : ℤ => (z : AlgebraicClosure (ZMod p)))
      (sum_legendreSign_product_eq_sign_mul_coefficient l hl u)
    simpa only [Int.cast_sum, Int.cast_mul] using h
  calc
    (∑ u : ZMod l,
        (∑ t : ZMod l,
          (legendreSign l (t * (u - t)) : AlgebraicClosure (ZMod p))) *
          w ^ u.val) =
      ∑ u : ZMod l,
        ((legendreSignInt l (-1) : AlgebraicClosure (ZMod p)) *
          (serreGaussCoefficient l u : AlgebraicClosure (ZMod p))) *
          w ^ u.val := by
      apply Finset.sum_congr rfl
      intro u _
      rw [hinner]
    _ = (legendreSignInt l (-1) : AlgebraicClosure (ZMod p)) *
        ∑ u : ZMod l,
          (serreGaussCoefficient l u : AlgebraicClosure (ZMod p)) *
            w ^ u.val := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro u _
      ring
    _ = (legendreSignInt l (-1) : AlgebraicClosure (ZMod p)) *
        (l : AlgebraicClosure (ZMod p)) := by
      rw [sum_serreGaussCoefficient_mul_rootPower l p hl w hw]

/-- Serre's first Gauss-sum lemma in the source exponent form. -/
theorem serreGaussSum_sq
    (hl : l ≠ 2) (w : AlgebraicClosure (ZMod p)) (hw : IsPrimitiveRoot w l) :
    serreGaussSum l p w ^ 2 =
      (((-1 : ℤ) ^ ((l - 1) / 2) : ℤ) : AlgebraicClosure (ZMod p)) *
        (l : AlgebraicClosure (ZMod p)) := by
  rw [serreGaussSum_sq_eq_legendreSign_neg_one_mul l p hl w hw,
    serre_theorem5_ii l hl]


/-- The project Legendre sign, cast into the algebraic closure used by the source Gauss sum. -/
noncomputable def serreLegendreMulCharAlgClosure
    (hl : l ≠ 2) : MulChar (ZMod l) (AlgebraicClosure (ZMod p)) :=
  (serreLegendreMulChar l hl).ringHomComp
    (Int.castRingHom (AlgebraicClosure (ZMod p)))

@[simp]
theorem serreLegendreMulCharAlgClosure_apply
    (hl : l ≠ 2) (x : ZMod l) :
    serreLegendreMulCharAlgClosure l p hl x =
      (legendreSign l x : AlgebraicClosure (ZMod p)) := by
  rfl

/-- The source-shaped Gauss sum is the generic Gauss sum of the same two characters. -/
theorem serreGaussSum_eq_gaussSum
    (hl : l ≠ 2) (w : AlgebraicClosure (ZMod p)) (hw : w ^ l = 1) :
    serreGaussSum l p w =
      gaussSum (serreLegendreMulCharAlgClosure l p hl)
        (serreRootAddChar l w hw) := by
  simp [gaussSum, serreGaussSum, serreLegendreMulCharAlgClosure,
    serreLegendreMulChar, serreRootAddChar_apply]

/--
The field-valued project Legendre character is fixed by the `p`-power operation
when `p` is odd. This is proved from the project's `±1` sign layer, not from a
packaged quadratic-character Frobenius theorem.
-/
theorem serreLegendreMulCharAlgClosure_pow_prime
    (hl : l ≠ 2) (hp : p ≠ 2) :
    (serreLegendreMulCharAlgClosure l p hl) ^ p =
      serreLegendreMulCharAlgClosure l p hl := by
  ext x
  rw [MulChar.pow_apply' _ (Fact.out : p.Prime).ne_zero]
  change
    ((legendreSign l (x : ZMod l) : AlgebraicClosure (ZMod p)) ^ p) =
      (legendreSign l (x : ZMod l) : AlgebraicClosure (ZMod p))
  rcases legendreSign_eq_one_or_neg_one_of_ne_zero l (x : ZMod l) x.ne_zero with h | h
  · rw [h]
    simp
  · have hpodd : Odd p := (Fact.out : p.Prime).odd_of_ne_two hp
    rw [h]
    norm_num [hpodd.neg_one_pow]

/--
Serre's second Gauss-sum computation in Frobenius form:
`y^p = (p/l) y`. The proof uses only generic Frobenius distribution and the
source reindexing by multiplication by `p`.
-/
theorem serreGaussSum_pow_prime
    (hl : l ≠ 2) (hp : p ≠ 2) (hlp : l ≠ p)
    (w : AlgebraicClosure (ZMod p)) (hw : IsPrimitiveRoot w l) :
    serreGaussSum l p w ^ p =
      (legendreSignInt l (p : ℤ) : AlgebraicClosure (ZMod p)) *
        serreGaussSum l p w := by
  let χ : MulChar (ZMod l) (AlgebraicClosure (ZMod p)) :=
    serreLegendreMulCharAlgClosure l p hl
  let ψ : AddChar (ZMod l) (AlgebraicClosure (ZMod p)) :=
    serreRootAddChar l w hw.pow_eq_one
  have hpmod : (p : ZMod l) ≠ 0 :=
    zmod_prime_cast_ne_zero_of_distinct p l hlp.symm
  have hpunit : IsUnit (p : ZMod l) := isUnit_iff_ne_zero.mpr hpmod
  have hχpow : χ ^ p = χ := by
    simpa [χ] using serreLegendreMulCharAlgClosure_pow_prime l p hl hp
  have hχp :
      χ (p : ZMod l) =
        (legendreSignInt l (p : ℤ) : AlgebraicClosure (ZMod p)) := by
    simp [χ, legendreSignInt, serreLegendreMulCharAlgClosure_apply]
  have hχp_sq : χ (p : ZMod l) ^ 2 = 1 := by
    rcases legendreSign_eq_one_or_neg_one_of_ne_zero l (p : ZMod l) hpmod with h | h
    · simp [χ, serreLegendreMulCharAlgClosure_apply, h]
    · simp [χ, serreLegendreMulCharAlgClosure_apply, h]
  rw [serreGaussSum_eq_gaussSum l p hl w hw.pow_eq_one]
  rw [_root_.gaussSum_frob p, hχpow, AddChar.pow_mulShift]
  have hshift := gaussSum_mulShift χ ψ hpunit.unit
  have hunit_spec : (hpunit.unit : ZMod l) = (p : ZMod l) := hpunit.unit_spec
  rw [hunit_spec] at hshift
  have hsolve :
      gaussSum χ (AddChar.mulShift ψ (p : ZMod l)) =
        χ (p : ZMod l) * gaussSum χ ψ := by
    calc
      gaussSum χ (AddChar.mulShift ψ (p : ZMod l)) =
          1 * gaussSum χ (AddChar.mulShift ψ (p : ZMod l)) := by simp
      _ = (χ (p : ZMod l) ^ 2) *
          gaussSum χ (AddChar.mulShift ψ (p : ZMod l)) := by rw [hχp_sq]
      _ = χ (p : ZMod l) *
          (χ (p : ZMod l) *
            gaussSum χ (AddChar.mulShift ψ (p : ZMod l))) := by ring
      _ = χ (p : ZMod l) * gaussSum χ ψ := by rw [hshift]
  rw [hsolve, hχp]


/-- The source Gauss sum is nonzero for distinct odd primes. -/
theorem serreGaussSum_ne_zero
    (hl : l ≠ 2) (hlp : l ≠ p)
    (w : AlgebraicClosure (ZMod p)) (hw : IsPrimitiveRoot w l) :
    serreGaussSum l p w ≠ 0 := by
  have hlz : (l : ZMod p) ≠ 0 :=
    zmod_prime_cast_ne_zero_of_distinct l p hlp
  have hlK : (l : AlgebraicClosure (ZMod p)) ≠ 0 := by
    change algebraMap (ZMod p) (AlgebraicClosure (ZMod p)) (l : ZMod p) ≠ 0
    simpa using
      (algebraMap (ZMod p) (AlgebraicClosure (ZMod p))).injective.ne hlz
  have hsign :
      (((-1 : ℤ) ^ ((l - 1) / 2) : ℤ) : AlgebraicClosure (ZMod p)) ≠ 0 := by
    push_cast
    exact pow_ne_zero _ (by norm_num)
  intro hy
  have hsq := serreGaussSum_sq l p hl w hw
  have hzero :
      (((-1 : ℤ) ^ ((l - 1) / 2) : ℤ) : AlgebraicClosure (ZMod p)) *
          (l : AlgebraicClosure (ZMod p)) = 0 := by
    rw [← hsq, hy]
    norm_num
  exact (mul_ne_zero hsign hlK) hzero

/-- Serre's second Gauss-sum lemma: `y^(p-1) = (p/l)`. -/
theorem serreGaussSum_pow_prime_sub_one
    (hl : l ≠ 2) (hp : p ≠ 2) (hlp : l ≠ p)
    (w : AlgebraicClosure (ZMod p)) (hw : IsPrimitiveRoot w l) :
    serreGaussSum l p w ^ (p - 1) =
      (legendreSignInt l (p : ℤ) : AlgebraicClosure (ZMod p)) := by
  have hy0 : serreGaussSum l p w ≠ 0 :=
    serreGaussSum_ne_zero l p hl hlp w hw
  have hp1 : 1 ≤ p := (Fact.out : p.Prime).one_le
  apply mul_right_cancel₀ hy0
  calc
    serreGaussSum l p w ^ (p - 1) * serreGaussSum l p w =
        serreGaussSum l p w ^ p := by
      rw [← pow_succ, Nat.sub_add_cancel hp1]
    _ = (legendreSignInt l (p : ℤ) : AlgebraicClosure (ZMod p)) *
        serreGaussSum l p w :=
      serreGaussSum_pow_prime l p hl hp hlp w hw


/-- Integer-input Legendre signs respect natural powers. -/
theorem legendreSignInt_pow
    (hp : p ≠ 2) (a : ℤ) (n : ℕ) :
    legendreSignInt p (a ^ n) = legendreSignInt p a ^ n := by
  induction n with
  | zero =>
      simp [serre_theorem5_i]
  | succ n ih =>
      rw [pow_succ, legendreSignInt_mul p hp, ih, pow_succ]


/--
Combining the two source Gauss-sum lemmas identifies the Legendre value of
`(-1)^((l-1)/2) * l` modulo `p` with the project Legendre sign of `p` modulo `l`.
-/
theorem sourceProduct_legendreValue_eq_otherSign
    (hl : l ≠ 2) (hp : p ≠ 2) (hlp : l ≠ p)
    (w : AlgebraicClosure (ZMod p)) (hw : IsPrimitiveRoot w l) :
    legendreValue p
        ((((-1 : ℤ) ^ ((l - 1) / 2)) * (l : ℤ) : ℤ) : ZMod p) =
      ((legendreSignInt l (p : ℤ) : ℤ) : ZMod p) := by
  let A : ℤ := ((-1 : ℤ) ^ ((l - 1) / 2)) * (l : ℤ)
  let y : AlgebraicClosure (ZMod p) := serreGaussSum l p w
  have hsq : y ^ 2 =
      (A : AlgebraicClosure (ZMod p)) := by
    dsimp [y, A]
    simpa only [Int.cast_mul, Int.cast_pow, Int.cast_neg, Int.cast_one, Int.cast_natCast] using
      serreGaussSum_sq l p hl w hw
  have hyexp : y ^ (p - 1) =
      (legendreSignInt l (p : ℤ) : AlgebraicClosure (ZMod p)) := by
    simpa [y] using serreGaussSum_pow_prime_sub_one l p hl hp hlp w hw
  have heven : Even (p - 1) := (Fact.out : p.Prime).even_sub_one hp
  have hhalf : 2 * ((p - 1) / 2) = p - 1 :=
    Nat.two_mul_div_two_of_even heven
  apply (algebraMap (ZMod p) (AlgebraicClosure (ZMod p))).injective
  change
    ((algebraMap (ZMod p) (AlgebraicClosure (ZMod p)))
        (legendreValue p (A : ZMod p))) =
      (algebraMap (ZMod p) (AlgebraicClosure (ZMod p)))
        ((legendreSignInt l (p : ℤ) : ℤ) : ZMod p)
  calc
    (algebraMap (ZMod p) (AlgebraicClosure (ZMod p)))
        (legendreValue p (A : ZMod p)) =
        ((A : AlgebraicClosure (ZMod p)) ^ ((p - 1) / 2)) := by
      simp [legendreValue]
    _ = (y ^ 2) ^ ((p - 1) / 2) := by rw [hsq]
    _ = y ^ (p - 1) := by
      rw [← pow_mul, hhalf]
    _ = (legendreSignInt l (p : ℤ) : AlgebraicClosure (ZMod p)) := hyexp
    _ = (algebraMap (ZMod p) (AlgebraicClosure (ZMod p)))
        ((legendreSignInt l (p : ℤ) : ℤ) : ZMod p) := by
      simp


/--
The preceding field-valued identity determines the integer-valued project Legendre sign of
the source product.
-/
theorem sourceProduct_legendreSign_eq_otherSign
    (hl : l ≠ 2) (hp : p ≠ 2) (hlp : l ≠ p)
    (w : AlgebraicClosure (ZMod p)) (hw : IsPrimitiveRoot w l) :
    legendreSignInt p
        (((-1 : ℤ) ^ ((l - 1) / 2)) * (l : ℤ)) =
      legendreSignInt l (p : ℤ) := by
  let A : ℤ := ((-1 : ℤ) ^ ((l - 1) / 2)) * (l : ℤ)
  change legendreSign p (A : ZMod p) =
    legendreSign l (((p : ℕ) : ℤ) : ZMod l)
  have hval :
      legendreValue p (A : ZMod p) =
        ((legendreSignInt l (p : ℤ) : ℤ) : ZMod p) := by
    simpa [A] using
      sourceProduct_legendreValue_eq_otherSign l p hl hp hlp w hw
  have hpmod : (p : ZMod l) ≠ 0 :=
    zmod_prime_cast_ne_zero_of_distinct p l hlp.symm
  rcases legendreSign_eq_one_or_neg_one_of_ne_zero l (p : ZMod l) hpmod with hother | hother
  · have hval_one : legendreValue p (A : ZMod p) = 1 := by
      simpa [legendreSignInt, hother] using hval
    have hA0 : (A : ZMod p) ≠ 0 := by
      intro hzero
      rw [hzero, legendreValue_zero p hp] at hval_one
      norm_num at hval_one
    have hother' : legendreSign l (((p : ℕ) : ℤ) : ZMod l) = 1 := by
      simpa using hother
    rw [hother']
    simp [legendreSign, hA0, hval_one]
  · have hp3 : 3 ≤ p := by
      have hp2 : 2 ≤ p := (Fact.out : p.Prime).two_le
      omega
    letI : Fact (2 < p) := ⟨by omega⟩
    have hval_neg : legendreValue p (A : ZMod p) = -1 := by
      simpa [legendreSignInt, hother] using hval
    have hA0 : (A : ZMod p) ≠ 0 := by
      intro hzero
      rw [hzero, legendreValue_zero p hp] at hval_neg
      norm_num at hval_neg
    have hval_ne : legendreValue p (A : ZMod p) ≠ 1 := by
      rw [hval_neg]
      exact ZMod.neg_one_ne_one
    have hother' : legendreSign l (((p : ℕ) : ℤ) : ZMod l) = -1 := by
      simpa using hother
    rw [hother']
    simp [legendreSign, hA0, hval_ne]


/-- Serre's Theorem 6: quadratic reciprocity for distinct odd primes. -/
theorem serre_theorem6
    (hl : l ≠ 2) (hp : p ≠ 2) (hlp : l ≠ p) :
    legendreSignInt p (l : ℤ) =
      legendreSignInt l (p : ℤ) *
        (-1 : ℤ) ^ (((l - 1) / 2) * ((p - 1) / 2)) := by
  obtain ⟨w, hw⟩ := exists_primitive_lth_root_algClosure l p hlp
  have hsource :=
    sourceProduct_legendreSign_eq_otherSign l p hl hp hlp w hw
  rw [legendreSignInt_mul p hp,
    legendreSignInt_pow p hp,
    serre_theorem5_ii p hp,
    ← pow_mul] at hsource
  rw [Nat.mul_comm ((p - 1) / 2) ((l - 1) / 2)] at hsource
  rcases Nat.even_or_odd (((l - 1) / 2) * ((p - 1) / 2)) with heven | hodd
  · have hs :
        (-1 : ℤ) ^ (((l - 1) / 2) * ((p - 1) / 2)) = 1 :=
      heven.neg_one_pow
    rw [hs] at hsource ⊢
    simpa using hsource
  · have hs :
        (-1 : ℤ) ^ (((l - 1) / 2) * ((p - 1) / 2)) = -1 :=
      hodd.neg_one_pow
    rw [hs] at hsource ⊢
    omega

end QuadraticReciprocity

end SerreNumberTheoryAI
