import SerreNumberTheoryAI.Formalization
import SerreNumberTheoryAI.Formalization.Chapter02.RootExistence
import SerreNumberTheoryAI.Blueprint
import SerreNumberTheoryAI.Blueprint.Chapter02.RootExistence
