import SerreNumberTheoryAI.Formalization.Chapter01.FiniteFields
import SerreNumberTheoryAI.Formalization.Chapter01.MultiplicativeGroup
import SerreNumberTheoryAI.Formalization.Chapter01.PowerSums
import SerreNumberTheoryAI.Formalization.Chapter01.Chevalley
import SerreNumberTheoryAI.Formalization.Chapter01.ChevalleyNontrivialZero
import SerreNumberTheoryAI.Formalization.Chapter01.ChevalleyQuadraticForm
import SerreNumberTheoryAI.Formalization.Chapter01.QuadraticElements
import SerreNumberTheoryAI.Formalization.Chapter01.LegendreSymbol
import SerreNumberTheoryAI.Formalization.Chapter01.LegendreTwo
import SerreNumberTheoryAI.Formalization.Chapter01.QuadraticReciprocity
import SerreNumberTheoryAI.Formalization.Chapter01.GaussLemma
import SerreNumberTheoryAI.Formalization.Chapter02.PadicIntegers
import SerreNumberTheoryAI.Formalization.Chapter02.PadicIntegerProperties
import SerreNumberTheoryAI.Formalization.Chapter02.PadicIntegerValuation
import SerreNumberTheoryAI.Formalization.Chapter02.PadicIntegerValuationAPI
import SerreNumberTheoryAI.Formalization.Chapter02.PadicIntegerMetric
import SerreNumberTheoryAI.Formalization.Chapter02.PadicIntegerMetricTopology
import SerreNumberTheoryAI.Formalization.Chapter02.PadicIntegerMetricCompletion
import SerreNumberTheoryAI.Formalization.Chapter02.PadicField
import SerreNumberTheoryAI.Formalization.Chapter02.PadicFieldTopology
import SerreNumberTheoryAI.Formalization.Chapter02.RootExistence
import SerreNumberTheoryAI.Formalization.Chapter02.PrimitiveHomogeneousZeros
import SerreNumberTheoryAI.Formalization.Chapter02.HenselLifting
import SerreNumberTheoryAI.Formalization.Chapter02.HenselTaylor
import SerreNumberTheoryAI.Formalization.Chapter02.HenselIteration
import SerreNumberTheoryAI.Formalization.Chapter02.HenselLimit
import SerreNumberTheoryAI.Formalization.Chapter02.HenselConclusion
import SerreNumberTheoryAI.Formalization.Chapter02.HenselLimitRoot
import SerreNumberTheoryAI.Formalization.Chapter02.HenselCorollary
import SerreNumberTheoryAI.Formalization.Chapter02.HenselQuadraticCorollary
import SerreNumberTheoryAI.Formalization.Chapter02.HenselQuadraticOdd
import SerreNumberTheoryAI.Formalization.Chapter02.HenselQuadraticOddResidue
import SerreNumberTheoryAI.Formalization.Chapter02.HenselQuadraticOddResidueExtractors
import SerreNumberTheoryAI.Formalization.Chapter02.HenselQuadraticOddDerivativeBridge
import SerreNumberTheoryAI.Formalization.Chapter02.HenselQuadraticOddSourceConsequences
import SerreNumberTheoryAI.Formalization.Chapter02.HenselQuadraticTwo
import SerreNumberTheoryAI.Formalization.Chapter02.HenselQuadraticTwoResidue
import SerreNumberTheoryAI.Formalization.Chapter02.PadicUnitFiltration
import SerreNumberTheoryAI.Formalization.Chapter02.PadicUnitFiltrationQuotient
import SerreNumberTheoryAI.Formalization.Chapter02.PadicUnitRoots

/-!
# Formalization root

このモジュールはAI版形式化の入口です。

数学的内容は章・節単位の子モジュールへ追加し、このファイルからimportします。
人間版 `are4c4/SerreNumberTheoryBlueprint` のformalizationを数学的ソースとしてimport・コピーしません。
-/

namespace SerreNumberTheoryAI

end SerreNumberTheoryAI
